name: sdk_core_dart
description: Layer 2 interceptors and primitives for Pinguteca SDKs in Dart
version: 0.0.1
repository: https://github.com/Pinguteca/sdk-core-dart
issue_tracker: https://github.com/Pinguteca/sdk-core-dart/issues
homepage: https://github.com/Pinguteca/sdk-core-dart

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  connectrpc: ^1.0.0

dev_dependencies:
  coverage: ^1.15.0
  lints: ^5.1.1
  test: ^1.31.1
